### ISSUE TITLE
Reading multiple AVRO files with different schema 

### ISSUE THREAD

**Issue by smunigati** [databricks/spark-avro#165] opened 2016-08-17 06:03 UTC
How do we load multiple AVRO files potentially with different schema(s)  in a single directory ? Is there any schema merge facility like we have while loading Parquet files ?

sqlContext.read.option("mergeSchema","true")

following does not work for AVRO files..
var df = sqlContext.read.option("mergeSchema","true").format("com.databricks.spark.avro").avro("/user/demo/")

**Comment by koertkuipers** [comment] 2016-10-10 19:18
this currently doesnt work despite avro having build in support for merging schemas.
the problem is that currently the GenericDatumReader is created without passing in an avro schema.

**Comment by JoshRosen** [comment] 2016-11-27 21:15
As of #195, we should now have the ability to use a user-provided Avro schema at read time, so I'm going to mark this as "fixed in 3.1.0". Please re-open if this problem hasn't been fully addressed.

**Closed by JoshRosen** 2016-11-27 21:15 UTC
